
name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/API_REST/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        # cache: 'npm'
    - run: |
        echo "Empezando con el Deployment"
    # Backend Steps
    - name: Install Backend Dependencies
      working-directory: apps/API_REST
      run: npm install
    - name: Build Application
      working-directory: apps/API_REST
      run: npm run build --if-present
    - name: Configuring Environment File
      working-directory: apps/API_REST
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    - name: STARTING/restarting application...
      working-directory: apps/API_REST/dist
      run: |
        pm2 restart api-test || pm2 start app.js --name api-test
            
