
name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/ecommerce_fe/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.20.0
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.0'
        # cache: 'npm'
    - run: |
        echo "Empezando con el Deployment"

    # Frontend Steps
    - name: Install Frontend Dependencies
      working-directory: apps/ecommerce_fe
      run: npm ci
    - name: Build Application
      working-directory: apps/ecommerce_fe
      run: npm run build --if-present
    
    - name: Configure Deployment Directory
      run: |
        sudo mkdir -p /var/www/test-client
        sudo chown -R $USER:$USER /var/www/test-client
        sudo chmod -R 755 /var/www/test-client

    - name: Deploy Frontend Application
      working-directory: apps/ecommerce_fe
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FRONTEND_FILE }}" > .env
        sudo cp -R dist/* /var/www/test-client
        sudo systemctl restart nginx
            
