
name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/ecommerce_fe/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        # cache: 'npm'
    - run: |
        echo "Empezando con el Deployment"

    # Frontend Steps
    - name: Install Frontend Dependencies
      working-directory: apps/ecommerce_fe
      run: npm install
    - name: Build Application
      working-directory: apps/ecommerce_fe
      run: npm run build --if-present
    - name: Realease Application
      working-directory: apps/ecommerce_fe
      run: |
        sudo touch .env
        sudo echo "${{ secrets.PROD_ENV_FRONTEND_FILE }}" > .env
        sudo cp -R dist/* /var/www/test-client
        sudo systemctl restart nginx
            
